# Variable pour stocker le token (a récuperer après le login)
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQyMjczYzVlLTQ5M2QtNDE3Mi1iMDA5LWNkNTAyYjU5MDI5ZSIsImVtYWlsIjoiYWxpY2VAZWR1dHJhY2suY29tIiwicm9sZSI6IlN0dWRlbnQiLCJpYXQiOjE3NjE3NTg1NjgsImV4cCI6MTc2MjM2MzM2OH0.OsSAimqxCzqo3xirOXLJORzD1Dd-RblvP2STnvW7kRU

### Recuperer tous les cours
GET http://localhost:3000/api/courses

### Créer un cours Intro C# (ID_ADA_LOVELACE)
POST http://localhost:3000/api/courses
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Introduction à C#",
  "description": "Apprendre les bases du langage C# et de la programmation orientée objet.",
  "instructorId": "e040e24f-5c21-41ab-b44f-d0fbffdc8d1c",
  "duration": 40,
  "maxStudents": 30,
  "price": 299.99,
  "level": "Beginner"
}

### Créer un cours ASP.NET Core (ID_ADA_LOVELACE)
POST http://localhost:3000/api/courses
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "ASP.NET Core Avancé",
  "description": "Maîtriser le développement d'API REST avec ASP.NET Core et Entity Framework.",
  "instructorId": "e040e24f-5c21-41ab-b44f-d0fbffdc8d1c",
  "duration": 60,
  "maxStudents": 25,
  "price": 499.99,
  "level": "Advanced"
}

### Créer un cours Physique Quantique (ID_MARIE_CURIE)
POST http://localhost:3000/api/courses
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Physique Quantique",
  "description": "Comprendre les principes fondamentaux de la mécanique quantique.",
  "instructorId": "b6a4d4b3-5d74-4728-b22c-fbfc6930c1a5",
  "duration": 80,
  "maxStudents": 20,
  "price": 599.99,
  "level": "Advanced"
}

### Créer un cours Maths Info (ID_ALBERT_EINSTEIN)
POST http://localhost:3000/api/courses
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Mathématiques pour l'Informatique",
  "description": "Algèbre linéaire, calcul différentiel et probabilités appliquées.",
  "instructorId": "d2136ea4-dda3-4851-9e60-95cd6c040029",
  "duration": 50,
  "maxStudents": 35,
  "price": 349.99,
  "level": "Intermediate"
}

### Créer un cours Intro Prog (ID_ADA_LOVELACE)
POST http://localhost:3000/api/courses
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Introduction à la Programmation",
  "description": "Premiers pas dans le monde de la programmation avec Python.",
  "instructorId": "e040e24f-5c21-41ab-b44f-d0fbffdc8d1c",
  "duration": 30,
  "maxStudents": 50,
  "price": 199.99,
  "level": "Beginner"
}

### Ne devrait pas marcher (erreur validation Zod, titre trop court) (ID_ADA_LOVELACE)
POST http://localhost:3000/api/courses
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "R",
  "description": "Premiers pas dans le monde de la programmation avec Python.",
  "instructorId": "e040e24f-5c21-41ab-b44f-d0fbffdc8d1c",
  "duration": 30,
  "maxStudents": 50,
  "price": 199.99,
  "level": "Beginner"
}

### Ne devrait pas marcher (creer un cours avec un id d'instructeur qui n'existe pas --> erreur 400)
POST http://localhost:3000/api/courses
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Cours Test",
  "description": "Premiers pas dans le monde de la programmation avec Python.",
  "instructorId": "af8a5ace-1d36-4235-a096-c2aba7048f73",
  "duration": 30,
  "maxStudents": 50,
  "price": 199.99,
  "level": "Beginner"
}

### Créer un cours MOCK
POST http://localhost:3000/api/courses
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Cours a effacer",
  "description": "C'est un test",
  "instructorId": "e040e24f-5c21-41ab-b44f-d0fbffdc8d1c",
  "duration": 30,
  "maxStudents": 50,
  "price": 199.99,
  "level": "Beginner"
}

### Modifier le cours MOCK
PUT http://localhost:3000/api/courses/9abb63a4-c2f7-4878-ac72-6d976fed1b79
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "description": "J'ai reussi a modifier la description."
}

### Récuperer le cours MOCK
GET http://localhost:3000/api/courses/9abb63a4-c2f7-4878-ac72-6d976fed1b79

### Suppression du cours MOCK
DELETE http://localhost:3000/api/courses/9abb63a4-c2f7-4878-ac72-6d976fed1b79
Authorization: Bearer {{token}}
