# Variable pour stocker le token (a récuperer après le login)
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQyMjczYzVlLTQ5M2QtNDE3Mi1iMDA5LWNkNTAyYjU5MDI5ZSIsImVtYWlsIjoiYWxpY2VAZWR1dHJhY2suY29tIiwicm9sZSI6IlN0dWRlbnQiLCJpYXQiOjE3NjE3NTg1NjgsImV4cCI6MTc2MjM2MzM2OH0.OsSAimqxCzqo3xirOXLJORzD1Dd-RblvP2STnvW7kRU

### Recuperer tous les instructeurs
GET http://localhost:3000/api/instructors

### Créer Marie Curie
POST http://localhost:3000/api/instructors
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "Marie",
  "lastName": "Curie",
  "specialty": "Physique et Chimie",
  "email": "marie.curie@edutrack.com",
  "hireDate": "2020-09-01"
}

### Créer Albert Einstein
POST http://localhost:3000/api/instructors
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "Albert",
  "lastName": "Einstein",
  "specialty": "Mathématiques et Physique",
  "email": "albert.einstein@edutrack.com",
  "hireDate": "2021-01-15"
}

### Créer Ada Lovelace
POST http://localhost:3000/api/instructors
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "Ada",
  "lastName": "Lovelace",
  "specialty": "Informatique et Programmation",
  "email": "ada.lovelace@edutrack.com",
  "hireDate": "2019-08-20"
}

### Créer un instructeur MOCK
POST http://localhost:3000/api/instructors
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "John",
  "lastName": "Doe",
  "specialty": "Informatique et Programmation",
  "email": "john.doe@edutrack.com",
  "hireDate": "2019-08-28"
}

### Modifier le instructeur MOCK
PUT http://localhost:3000/api/instructors/0f993529-0a25-4fc8-95e5-0870d597342b
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "specialty": "Modification OK"
}

### Récuperer le instructeur MOCK
GET http://localhost:3000/api/instructors/0f993529-0a25-4fc8-95e5-0870d597342b

### Suppression du instructeur MOCK
DELETE http://localhost:3000/api/instructors/0f993529-0a25-4fc8-95e5-0870d597342b
Authorization: Bearer {{token}}
