### Crée utilisateur Alice
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "alice.student",
  "email": "alice@edutrack.com",
  "password": "Alice123!",
  "firstName": "Alice",
  "lastName": "Martin"
}

### Crée un utilsateur avec le même username que Alice (erreur 400)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "alice.student",
  "email": "alice@unautrecourriel.com",
  "password": "ça_ne_marchera_pas",
  "firstName": "Alice",
  "lastName": "Copie"
}

### Se logger en tant qu'Alice
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "alice@edutrack.com",
    "password": "Alice123!"
}

### Se logger avec un email inexistant
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "existe_pas@test.com",
    "password": "peu.importe"
}